mod qpack_data;

use std::{
  collections::BTreeMap,
  env, fs,
  path::{Path, PathBuf},
  process,
};

const GENERATED_HEADER: &str = "\
// @generated by `cargo run -p xtask -- qpack-codegen`; do not edit by hand.
#![allow(dead_code)]
#![allow(missing_docs)]

";

fn main() {
  if let Err(err) = run() {
    eprintln!("xtask: {err}");
    process::exit(1);
  }
}

fn run() -> Result<(), Box<dyn std::error::Error>> {
  let mut args = env::args().skip(1);
  let Some(command) = args.next() else {
    print_help();
    return Ok(());
  };

  match command.as_str() {
    "qpack-codegen" => {
      let check = match args.next().as_deref() {
        None => false,
        Some("--check") => true,
        Some(other) => return Err(format!("unexpected qpack-codegen argument: {other}").into()),
      };
      if args.next().is_some() {
        return Err("too many qpack-codegen arguments".into());
      }
      qpack_codegen(check)?;
    }
    "-h" | "--help" | "help" => print_help(),
    other => return Err(format!("unknown command: {other}").into()),
  }

  Ok(())
}

fn print_help() {
  println!(
    "\
Usage:
  cargo run -p xtask -- qpack-codegen
  cargo run -p xtask -- qpack-codegen --check
"
  );
}

fn qpack_codegen(check: bool) -> Result<(), Box<dyn std::error::Error>> {
  let root = workspace_root()?;
  let qpack_dir = root.join("http3-proto/src/qpack");

  let huffman_dir = qpack_dir.join("huffman");
  let static_table_dir = qpack_dir.join("static_table");

  let huffman = generate_huffman(qpack_data::HUFFMAN_CODES)?;
  let static_table = generate_static_table(qpack_data::STATIC_TABLE_ENTRIES)?;

  write_generated(&huffman_dir.join("generated.rs"), &huffman, check)?;
  write_generated(&static_table_dir.join("generated.rs"), &static_table, check)?;

  Ok(())
}

fn workspace_root() -> Result<PathBuf, Box<dyn std::error::Error>> {
  let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
  manifest_dir
    .parent()
    .map(Path::to_path_buf)
    .ok_or_else(|| "xtask manifest has no parent directory".into())
}

fn write_generated(
  path: &Path,
  content: &str,
  check: bool,
) -> Result<(), Box<dyn std::error::Error>> {
  if check {
    let existing = fs::read_to_string(path)?;
    if existing != content {
      return Err(
        format!(
          "{} is stale; run `cargo run -p xtask -- qpack-codegen`",
          path.display()
        )
        .into(),
      );
    }
  } else {
    fs::write(path, content)?;
  }

  Ok(())
}

#[derive(Clone, Copy)]
enum Edge {
  Empty,
  Node(usize),
  Symbol(usize),
}

#[derive(Clone, Copy)]
struct BuildNode {
  zero: Edge,
  one: Edge,
}

impl BuildNode {
  fn empty() -> Self {
    Self {
      zero: Edge::Empty,
      one: Edge::Empty,
    }
  }

  fn edge(&self, bit: u32) -> Edge {
    if bit == 0 { self.zero } else { self.one }
  }

  fn set_edge(&mut self, bit: u32, edge: Edge) {
    if bit == 0 {
      self.zero = edge;
    } else {
      self.one = edge;
    }
  }
}

fn generate_huffman(codes: &[(u32, u8)]) -> Result<String, Box<dyn std::error::Error>> {
  if codes.len() != 257 {
    return Err(format!("expected 257 Huffman codes, found {}", codes.len()).into());
  }

  let mut nodes = vec![BuildNode::empty()];

  for (symbol, &(code, len)) in codes.iter().enumerate() {
    let mut node = 0usize;
    for depth in 0..u32::from(len) {
      let remaining = u32::from(len)
        .checked_sub(depth)
        .and_then(|value| value.checked_sub(1))
        .ok_or("invalid Huffman code length")?;
      let bit = (code >> remaining) & 1;

      if depth + 1 == u32::from(len) {
        if !matches!(nodes[node].edge(bit), Edge::Empty) {
          return Err(format!("duplicate Huffman edge for symbol {symbol}").into());
        }
        nodes[node].set_edge(bit, Edge::Symbol(symbol));
      } else {
        let next = match nodes[node].edge(bit) {
          Edge::Node(next) => next,
          Edge::Empty => {
            let next = nodes.len();
            nodes[node].set_edge(bit, Edge::Node(next));
            nodes.push(BuildNode::empty());
            next
          }
          Edge::Symbol(_) => {
            return Err(format!("Huffman symbol {symbol} extends a leaf").into());
          }
        };
        node = next;
      }
    }
  }

  let mut out = String::from(GENERATED_HEADER);
  out.push_str(
    "\
#[derive(Clone, Copy)]
pub(super) struct HuffmanNode {
  zero: u16,
  one: u16,
}

pub(super) enum HuffmanStep {
  Node(u16),
  Symbol(usize),
  Invalid,
}

pub(super) const HUFFMAN_ROOT: u16 = 0;
const SYMBOL_FLAG: u16 = 0x8000;
const INVALID_EDGE: u16 = 0xffff;

",
  );

  out.push_str("#[rustfmt::skip]\npub(super) static CODE_LENGTHS: [u8; 256] = [\n");
  for chunk in codes[..256].chunks(16) {
    out.push_str("  ");
    for (index, &(_, len)) in chunk.iter().enumerate() {
      if index > 0 {
        out.push(' ');
      }
      out.push_str(&format!("{len},"));
    }
    out.push('\n');
  }
  out.push_str("];\n\n");

  out.push_str(&format!(
    "static HUFFMAN_NODES: [HuffmanNode; {}] = [\n",
    nodes.len()
  ));
  for node in &nodes {
    out.push_str(&format!(
      "  HuffmanNode {{\n    zero: {},\n    one: {},\n  }},\n",
      edge_literal(node.zero)?,
      edge_literal(node.one)?
    ));
  }
  out.push_str("];\n\n");

  out.push_str(
    "\
#[inline]
pub(super) fn step(node: u16, bit: u32) -> HuffmanStep {
  let Some(node) = HUFFMAN_NODES.get(usize::from(node)) else {
    return HuffmanStep::Invalid;
  };
  let next = if bit == 0 { node.zero } else { node.one };
  decode_edge(next)
}

#[inline]
fn decode_edge(edge: u16) -> HuffmanStep {
  if edge == INVALID_EDGE {
    HuffmanStep::Invalid
  } else if edge & SYMBOL_FLAG == SYMBOL_FLAG {
    HuffmanStep::Symbol(usize::from(edge & !SYMBOL_FLAG))
  } else {
    HuffmanStep::Node(edge)
  }
}
",
  );

  Ok(out)
}

fn edge_literal(edge: Edge) -> Result<String, Box<dyn std::error::Error>> {
  match edge {
    Edge::Empty => Ok("INVALID_EDGE".to_owned()),
    Edge::Node(node) => Ok(format!("{}u16", u16::try_from(node)?)),
    Edge::Symbol(symbol) => {
      let symbol = u16::try_from(symbol)?;
      if symbol == 0 {
        Ok("SYMBOL_FLAG".to_owned())
      } else {
        Ok(format!("SYMBOL_FLAG | {symbol}u16"))
      }
    }
  }
}

fn generate_static_table(entries: &[(&str, &str)]) -> Result<String, Box<dyn std::error::Error>> {
  if entries.len() > usize::from(u8::MAX) {
    return Err("static table does not fit in u8 indices".into());
  }

  let mut by_name = BTreeMap::<&str, Vec<(&str, usize)>>::new();
  for (index, &(name, value)) in entries.iter().enumerate() {
    by_name.entry(name).or_default().push((value, index));
  }

  let mut out = String::from(GENERATED_HEADER);

  out.push_str(&format!(
    "pub(super) const STATIC_TABLE_LEN: usize = {};\n\n",
    entries.len()
  ));

  out.push_str(
    "\
#[rustfmt::skip]
#[inline]
pub(super) fn entry(index: usize) -> Option<(&'static str, &'static str)> {
  match index {
",
  );

  for (index, &(name, value)) in entries.iter().enumerate() {
    out.push_str(&format!(
      "    {index} => Some(({}, {})),\n",
      rust_string_literal(name),
      rust_string_literal(value)
    ));
  }

  out.push_str("    _ => None,\n  }\n}\n\n");

  out.push_str(
    "\
#[inline]
pub(super) fn find_name_value(name: &str, value: &str) -> Option<usize> {
  match name {
",
  );

  for (name, values) in &by_name {
    out.push_str(&format!(
      "    {} => match value {{\n",
      rust_string_literal(name)
    ));
    for (value, index) in values {
      out.push_str(&format!(
        "      {} => Some({index}),\n",
        rust_string_literal(value)
      ));
    }
    out.push_str("      _ => None,\n    },\n");
  }

  out.push_str("    _ => None,\n  }\n}\n\n");
  out.push_str(
    "\
#[inline]
pub(super) fn find_name(name: &str) -> Option<usize> {
  match name {
",
  );

  for (name, values) in &by_name {
    let Some((_, first_index)) = values.first() else {
      return Err("empty static-table name group".into());
    };
    out.push_str(&format!(
      "    {} => Some({first_index}),\n",
      rust_string_literal(name)
    ));
  }

  out.push_str("    _ => None,\n  }\n}\n");

  Ok(out)
}

fn rust_string_literal(value: &str) -> String {
  let mut out = String::from("\"");
  for ch in value.chars() {
    match ch {
      '\\' => out.push_str("\\\\"),
      '"' => out.push_str("\\\""),
      '\n' => out.push_str("\\n"),
      '\r' => out.push_str("\\r"),
      '\t' => out.push_str("\\t"),
      other => out.push(other),
    }
  }
  out.push('"');
  out
}
