mod doc_check;
mod handshake_diff;
mod qpack_data;
mod quote_check;

use std::{
  collections::BTreeMap,
  env, fs,
  path::{Path, PathBuf},
  process,
};

/// Shared error type for every `xtask` subcommand.
type Error = Box<dyn std::error::Error>;

const GENERATED_HEADER: &str = "\
// @generated by `cargo run -p xtask -- qpack-codegen`; do not edit by hand.
#![allow(dead_code)]
#![allow(missing_docs)]

";

// The bench-table file is pulled in with `include!`, so it cannot carry inner
// attributes (`#![…]`); it gets a plain comment banner instead.
const GENERATED_INCLUDE_HEADER: &str = "\
// @generated by `cargo run -p xtask -- qpack-codegen`; do not edit by hand.
// Included by `benches/qpack_static_lookup.rs`; not a standalone module.

";

fn main() {
  if let Err(err) = run() {
    eprintln!("xtask: {err}");
    process::exit(1);
  }
}

fn run() -> Result<(), Box<dyn std::error::Error>> {
  let mut args = env::args().skip(1);
  let Some(command) = args.next() else {
    print_help();
    return Ok(());
  };

  match command.as_str() {
    "qpack-codegen" => {
      let check = match args.next().as_deref() {
        None => false,
        Some("--check") => true,
        Some(other) => return Err(format!("unexpected qpack-codegen argument: {other}").into()),
      };
      if args.next().is_some() {
        return Err("too many qpack-codegen arguments".into());
      }
      qpack_codegen(check)?;
    }
    "handshake-diff" => {
      let Some(base) = args.next() else {
        return Err("handshake-diff needs a base revision".into());
      };
      let head = args.next();
      if args.next().is_some() {
        return Err("too many handshake-diff arguments".into());
      }
      handshake_diff::run(&base, head.as_deref())?;
    }
    "quote-check" => {
      let mut fetch = false;
      let mut include_ignored = false;
      let mut dir = None;
      for arg in args {
        match arg.as_str() {
          "--fetch" => fetch = true,
          "--include-ignored" => include_ignored = true,
          other if other.starts_with('-') => {
            return Err(format!("unexpected quote-check argument: {other}").into());
          }
          other if dir.is_none() => dir = Some(other.to_string()),
          _ => return Err("too many quote-check arguments".into()),
        }
      }
      quote_check::run(dir.as_deref(), fetch, include_ignored)?;
    }
    "doc-check" => {
      let mut require_all = false;
      let mut bless = false;
      for arg in args {
        match arg.as_str() {
          "--require-all" => require_all = true,
          "--bless" => bless = true,
          other => return Err(format!("unexpected doc-check argument: {other}").into()),
        }
      }
      doc_check::run(require_all, bless)?;
    }
    "-h" | "--help" | "help" => print_help(),
    other => return Err(format!("unknown command: {other}").into()),
  }

  Ok(())
}

fn print_help() {
  println!(
    "\
Usage:
  cargo run -p xtask -- qpack-codegen
  cargo run -p xtask -- qpack-codegen --check
  cargo run -p xtask -- handshake-diff <base-rev> [head-rev]
  cargo run -p xtask -- quote-check [--fetch] [--include-ignored] [<spec-dir>]
  cargo run -p xtask -- doc-check [--require-all] [--bless]

`handshake-diff` runs `handshake-corpus` against two revisions of
`websocket-proto` and reports the verdicts that moved, grouped by
(role, field, reason), plus whether equivalent spellings of one field value
still reach one verdict. `head-rev` defaults to the working tree. It works in
$TMPDIR and leaves the repository untouched.

`quote-check` reads every RFC quotation out of the workspace's `.rs` and `.md`
comments and fails on any whose characters are not the spec's own — a
re-cased sentence, a reworded one. It is case-SENSITIVE and joins wrapped
comment lines, which is what the manual sweeps that missed this defect did
not do.

<spec-dir> holds the `.txt` rendering of each RFC, named `rfcNNNN.txt`; they
are at https://www.rfc-editor.org/rfc/rfcNNNN.txt. It defaults to `{}/`,
which is gitignored. `--fetch` downloads the RFCs this workspace cites into
it with `curl`; nothing else here touches the network. `--include-ignored`
additionally scans paths git ignores, such as `docs/`, which are skipped by
default because they exist on a developer's disk and not in CI.

`doc-check` is `quote-check`'s sibling: checks over what this workspace's
documentation CLAIMS rather than quotes — doc continuity, table-verdict
vocabulary, and path-qualified callee assertions. One needs rustdoc's JSON
output, which is nightly-only; the other two run on any toolchain. A check
that cannot run on the current toolchain says so by name instead of silently
not running. `--require-all` turns a SKIPPED check into a failure, which is
what CI's nightly job passes so an edit to that job cannot quietly drop a
check while the report still exits 0. `--bless` lets a check rewrite what it
flags instead of only reporting it, where the check supports it.
",
    quote_check::DEFAULT_DIR
  );
}

fn qpack_codegen(check: bool) -> Result<(), Box<dyn std::error::Error>> {
  let root = workspace_root()?;
  let qpack_dir = root.join("http3-proto/src/qpack");

  let huffman_dir = qpack_dir.join("huffman");
  let static_table_dir = qpack_dir.join("static_table");

  let huffman = generate_huffman(qpack_data::HUFFMAN_CODES)?;
  let static_table = generate_static_table(qpack_data::STATIC_TABLE_ENTRIES)?;
  let bench_lookup = generate_bench_static_lookup(qpack_data::STATIC_TABLE_ENTRIES)?;

  write_generated(&huffman_dir.join("generated.rs"), &huffman, check)?;
  write_generated(&static_table_dir.join("generated.rs"), &static_table, check)?;
  write_generated(
    &root.join("http3-proto/benches/generated_static_lookup.rs"),
    &bench_lookup,
    check,
  )?;

  Ok(())
}

fn workspace_root() -> Result<PathBuf, Box<dyn std::error::Error>> {
  let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
  manifest_dir
    .parent()
    .map(Path::to_path_buf)
    .ok_or_else(|| "xtask manifest has no parent directory".into())
}

fn write_generated(
  path: &Path,
  content: &str,
  check: bool,
) -> Result<(), Box<dyn std::error::Error>> {
  if check {
    let existing = fs::read_to_string(path)?;
    if existing != content {
      return Err(
        format!(
          "{} is stale; run `cargo run -p xtask -- qpack-codegen`",
          path.display()
        )
        .into(),
      );
    }
  } else {
    fs::write(path, content)?;
  }

  Ok(())
}

#[derive(Clone, Copy)]
enum Edge {
  Empty,
  Node(usize),
  Symbol(usize),
}

#[derive(Clone, Copy)]
struct BuildNode {
  zero: Edge,
  one: Edge,
}

impl BuildNode {
  fn empty() -> Self {
    Self {
      zero: Edge::Empty,
      one: Edge::Empty,
    }
  }

  fn edge(&self, bit: u32) -> Edge {
    if bit == 0 { self.zero } else { self.one }
  }

  fn set_edge(&mut self, bit: u32, edge: Edge) {
    if bit == 0 {
      self.zero = edge;
    } else {
      self.one = edge;
    }
  }
}

fn generate_huffman(codes: &[(u32, u8)]) -> Result<String, Box<dyn std::error::Error>> {
  if codes.len() != 257 {
    return Err(format!("expected 257 Huffman codes, found {}", codes.len()).into());
  }

  let mut nodes = vec![BuildNode::empty()];

  for (symbol, &(code, len)) in codes.iter().enumerate() {
    let mut node = 0usize;
    for depth in 0..u32::from(len) {
      let remaining = u32::from(len)
        .checked_sub(depth)
        .and_then(|value| value.checked_sub(1))
        .ok_or("invalid Huffman code length")?;
      let bit = (code >> remaining) & 1;

      if depth + 1 == u32::from(len) {
        if !matches!(nodes[node].edge(bit), Edge::Empty) {
          return Err(format!("duplicate Huffman edge for symbol {symbol}").into());
        }
        nodes[node].set_edge(bit, Edge::Symbol(symbol));
      } else {
        let next = match nodes[node].edge(bit) {
          Edge::Node(next) => next,
          Edge::Empty => {
            let next = nodes.len();
            nodes[node].set_edge(bit, Edge::Node(next));
            nodes.push(BuildNode::empty());
            next
          }
          Edge::Symbol(_) => {
            return Err(format!("Huffman symbol {symbol} extends a leaf").into());
          }
        };
        node = next;
      }
    }
  }

  // The RFC 7541 Huffman tree is complete, so a finished build has no missing
  // children; `INVALID_EDGE` (and the branch that tests for it) is only emitted
  // when some edge is actually `Empty`.
  let has_empty_edge = nodes
    .iter()
    .any(|node| matches!(node.zero, Edge::Empty) || matches!(node.one, Edge::Empty));

  let mut out = String::from(GENERATED_HEADER);
  out.push_str(
    "\
#[derive(Clone, Copy)]
pub(super) struct HuffmanNode {
  zero: u16,
  one: u16,
}

pub(super) enum HuffmanStep {
  Node(u16),
  Symbol(usize),
  Invalid,
}

pub(super) const HUFFMAN_ROOT: u16 = 0;
const SYMBOL_FLAG: u16 = 0x8000;
",
  );
  if has_empty_edge {
    out.push_str("const INVALID_EDGE: u16 = 0xffff;\n");
  }
  out.push('\n');

  out.push_str("#[rustfmt::skip]\npub(super) static CODE_LENGTHS: [u8; 256] = [\n");
  for chunk in codes[..256].chunks(16) {
    out.push_str("  ");
    for (index, &(_, len)) in chunk.iter().enumerate() {
      if index > 0 {
        out.push(' ');
      }
      out.push_str(&format!("{len},"));
    }
    out.push('\n');
  }
  out.push_str("];\n\n");

  out.push_str(&format!(
    "static HUFFMAN_NODES: [HuffmanNode; {}] = [\n",
    nodes.len()
  ));
  for node in &nodes {
    out.push_str(&format!(
      "  HuffmanNode {{\n    zero: {},\n    one: {},\n  }},\n",
      edge_literal(node.zero)?,
      edge_literal(node.one)?
    ));
  }
  out.push_str("];\n\n");

  out.push_str(
    "\
#[inline]
pub(super) fn step(node: u16, bit: u32) -> HuffmanStep {
  let Some(node) = HUFFMAN_NODES.get(usize::from(node)) else {
    return HuffmanStep::Invalid;
  };
  let next = if bit == 0 { node.zero } else { node.one };
  decode_edge(next)
}

#[inline]
fn decode_edge(edge: u16) -> HuffmanStep {
",
  );
  if has_empty_edge {
    out.push_str(
      "  if edge == INVALID_EDGE {
    HuffmanStep::Invalid
  } else if edge & SYMBOL_FLAG == SYMBOL_FLAG {
    HuffmanStep::Symbol(usize::from(edge & !SYMBOL_FLAG))
  } else {
    HuffmanStep::Node(edge)
  }
}
",
    );
  } else {
    out.push_str(
      "  if edge & SYMBOL_FLAG == SYMBOL_FLAG {
    HuffmanStep::Symbol(usize::from(edge & !SYMBOL_FLAG))
  } else {
    HuffmanStep::Node(edge)
  }
}
",
    );
  }

  Ok(out)
}

fn edge_literal(edge: Edge) -> Result<String, Box<dyn std::error::Error>> {
  match edge {
    Edge::Empty => Ok("INVALID_EDGE".to_owned()),
    Edge::Node(node) => Ok(format!("{}u16", u16::try_from(node)?)),
    Edge::Symbol(symbol) => {
      let symbol = u16::try_from(symbol)?;
      if symbol == 0 {
        Ok("SYMBOL_FLAG".to_owned())
      } else {
        Ok(format!("SYMBOL_FLAG | {symbol}u16"))
      }
    }
  }
}

fn generate_static_table(entries: &[(&str, &str)]) -> Result<String, Box<dyn std::error::Error>> {
  if entries.len() > usize::from(u8::MAX) {
    return Err("static table does not fit in u8 indices".into());
  }

  let mut by_name = BTreeMap::<&str, Vec<(&str, usize)>>::new();
  for (index, &(name, value)) in entries.iter().enumerate() {
    by_name.entry(name).or_default().push((value, index));
  }

  let mut out = String::from(GENERATED_HEADER);

  // Only `tests` consult the table length, so the generated item is test-gated
  // to keep test-only data out of the production build.
  out.push_str(&format!(
    "#[cfg(test)]\npub(super) const STATIC_TABLE_LEN: usize = {};\n\n",
    entries.len()
  ));

  // Each lookup is a `fn … { match scrutinee { <arms> _ => None } }`; the
  // signature and the `match`/`_ => None` scaffolding are identical, so only the
  // attributes, signature, scrutinee, and arm bodies vary per function.
  let emit_match = |out: &mut String, attrs: &str, signature: &str, scrutinee: &str, arms: &str| {
    out.push_str(attrs);
    out.push_str(signature);
    out.push_str(" {\n  match ");
    out.push_str(scrutinee);
    out.push_str(" {\n");
    out.push_str(arms);
    out.push_str("    _ => None,\n  }\n}\n");
  };

  let mut entry_arms = String::new();
  for (index, &(name, value)) in entries.iter().enumerate() {
    entry_arms.push_str(&format!(
      "    {index} => Some(({}, {})),\n",
      rust_string_literal(name),
      rust_string_literal(value)
    ));
  }
  emit_match(
    &mut out,
    "#[rustfmt::skip]\n#[inline]\n",
    "pub(super) fn entry(index: usize) -> Option<(&'static str, &'static str)>",
    "index",
    &entry_arms,
  );
  out.push('\n');

  let mut name_value_arms = String::new();
  for (name, values) in &by_name {
    name_value_arms.push_str(&format!(
      "    {} => match value {{\n",
      rust_string_literal(name)
    ));
    for (value, index) in values {
      name_value_arms.push_str(&format!(
        "      {} => Some({index}),\n",
        rust_string_literal(value)
      ));
    }
    name_value_arms.push_str("      _ => None,\n    },\n");
  }
  emit_match(
    &mut out,
    "#[inline]\n",
    "pub(super) fn find_name_value(name: &str, value: &str) -> Option<usize>",
    "name",
    &name_value_arms,
  );
  out.push('\n');

  let mut name_arms = String::new();
  for (name, values) in &by_name {
    let Some((_, first_index)) = values.first() else {
      return Err("empty static-table name group".into());
    };
    name_arms.push_str(&format!(
      "    {} => Some({first_index}),\n",
      rust_string_literal(name)
    ));
  }
  emit_match(
    &mut out,
    "#[inline]\n",
    "pub(super) fn find_name(name: &str) -> Option<usize>",
    "name",
    &name_arms,
  );

  Ok(out)
}

/// Emits the `phf` lookup tables the QPACK static-lookup benchmark compares the
/// crate's hand-written `match` against, sourced from the same canonical entries
/// (so the two can never drift). The file is `include!`d by the bench.
fn generate_bench_static_lookup(
  entries: &[(&str, &str)],
) -> Result<String, Box<dyn std::error::Error>> {
  let mut out = String::from(GENERATED_INCLUDE_HEADER);

  out.push_str(
    "static PHF_NAME_VALUE: phf::Map<(&'static str, &'static str), usize> = phf::phf_map! {\n",
  );
  for (index, &(name, value)) in entries.iter().enumerate() {
    out.push_str(&format!(
      "  ({}, {}) => {index}usize,\n",
      rust_string_literal(name),
      rust_string_literal(value)
    ));
  }
  out.push_str("};\n\n");

  out.push_str("static PHF_NAME: phf::Map<&'static str, usize> = phf::phf_map! {\n");
  let mut seen = std::collections::HashSet::new();
  for (index, &(name, _)) in entries.iter().enumerate() {
    if seen.insert(name) {
      out.push_str(&format!(
        "  {} => {index}usize,\n",
        rust_string_literal(name)
      ));
    }
  }
  out.push_str("};\n");

  Ok(out)
}

fn rust_string_literal(value: &str) -> String {
  let mut out = String::from("\"");
  for ch in value.chars() {
    match ch {
      '\\' => out.push_str("\\\\"),
      '"' => out.push_str("\\\""),
      '\n' => out.push_str("\\n"),
      '\r' => out.push_str("\\r"),
      '\t' => out.push_str("\\t"),
      other => out.push(other),
    }
  }
  out.push('"');
  out
}
