// @generated by `cargo run -p xtask -- qpack-codegen`; do not edit by hand.
#![allow(dead_code)]
#![allow(missing_docs)]

#[derive(Clone, Copy)]
pub(super) struct HuffmanNode {
  zero: u16,
  one: u16,
}

pub(super) enum HuffmanStep {
  Node(u16),
  Symbol(usize),
  Invalid,
}

pub(super) const HUFFMAN_ROOT: u16 = 0;
const SYMBOL_FLAG: u16 = 0x8000;
const INVALID_EDGE: u16 = 0xffff;

#[rustfmt::skip]
pub(super) static CODE_LENGTHS: [u8; 256] = [
  13, 23, 28, 28, 28, 28, 28, 28, 28, 24, 30, 28, 28, 30, 28, 28,
  28, 28, 28, 28, 28, 28, 30, 28, 28, 28, 28, 28, 28, 28, 28, 28,
  6, 10, 10, 12, 13, 6, 8, 11, 10, 10, 8, 11, 8, 6, 6, 6,
  5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 7, 8, 15, 6, 12, 10,
  13, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
  7, 7, 7, 7, 7, 7, 7, 7, 8, 7, 8, 13, 19, 13, 14, 6,
  15, 5, 6, 5, 6, 5, 6, 6, 6, 5, 7, 7, 6, 6, 6, 5,
  6, 7, 6, 5, 5, 6, 7, 7, 7, 7, 7, 15, 11, 14, 13, 28,
  20, 22, 20, 20, 22, 22, 22, 23, 22, 23, 23, 23, 23, 23, 24, 23,
  24, 24, 22, 23, 24, 23, 23, 23, 23, 21, 22, 23, 22, 23, 23, 24,
  22, 21, 20, 22, 22, 23, 23, 21, 23, 22, 22, 24, 21, 22, 23, 23,
  21, 21, 22, 21, 23, 22, 23, 23, 20, 22, 22, 22, 23, 22, 22, 23,
  26, 26, 20, 19, 22, 23, 22, 25, 26, 26, 26, 27, 27, 26, 24, 25,
  19, 21, 26, 27, 27, 26, 27, 24, 21, 21, 26, 26, 28, 27, 27, 27,
  20, 24, 20, 21, 22, 21, 21, 23, 22, 22, 25, 25, 24, 24, 26, 23,
  26, 27, 26, 26, 27, 27, 27, 27, 27, 28, 27, 27, 27, 27, 27, 26,
];

static HUFFMAN_NODES: [HuffmanNode; 256] = [
  HuffmanNode {
    zero: 66u16,
    one: 1u16,
  },
  HuffmanNode {
    zero: 93u16,
    one: 2u16,
  },
  HuffmanNode {
    zero: 104u16,
    one: 3u16,
  },
  HuffmanNode {
    zero: 119u16,
    one: 4u16,
  },
  HuffmanNode {
    zero: 144u16,
    one: 5u16,
  },
  HuffmanNode {
    zero: 75u16,
    one: 6u16,
  },
  HuffmanNode {
    zero: 123u16,
    one: 7u16,
  },
  HuffmanNode {
    zero: 71u16,
    one: 8u16,
  },
  HuffmanNode {
    zero: 77u16,
    one: 9u16,
  },
  HuffmanNode {
    zero: 73u16,
    one: 10u16,
  },
  HuffmanNode {
    zero: 11u16,
    one: 13u16,
  },
  HuffmanNode {
    zero: 12u16,
    one: 102u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG,
    one: SYMBOL_FLAG | 36u16,
  },
  HuffmanNode {
    zero: 127u16,
    one: 14u16,
  },
  HuffmanNode {
    zero: 128u16,
    one: 15u16,
  },
  HuffmanNode {
    zero: 98u16,
    one: 16u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 123u16,
    one: 17u16,
  },
  HuffmanNode {
    zero: 124u16,
    one: 18u16,
  },
  HuffmanNode {
    zero: 150u16,
    one: 19u16,
  },
  HuffmanNode {
    zero: 20u16,
    one: 25u16,
  },
  HuffmanNode {
    zero: 199u16,
    one: 21u16,
  },
  HuffmanNode {
    zero: 216u16,
    one: 22u16,
  },
  HuffmanNode {
    zero: 23u16,
    one: 162u16,
  },
  HuffmanNode {
    zero: 24u16,
    one: 161u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 1u16,
    one: SYMBOL_FLAG | 135u16,
  },
  HuffmanNode {
    zero: 167u16,
    one: 26u16,
  },
  HuffmanNode {
    zero: 41u16,
    one: 27u16,
  },
  HuffmanNode {
    zero: 191u16,
    one: 28u16,
  },
  HuffmanNode {
    zero: 211u16,
    one: 29u16,
  },
  HuffmanNode {
    zero: 229u16,
    one: 30u16,
  },
  HuffmanNode {
    zero: 31u16,
    one: 45u16,
  },
  HuffmanNode {
    zero: 32u16,
    one: 38u16,
  },
  HuffmanNode {
    zero: 33u16,
    one: 35u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 254u16,
    one: 34u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 2u16,
    one: SYMBOL_FLAG | 3u16,
  },
  HuffmanNode {
    zero: 36u16,
    one: 37u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 4u16,
    one: SYMBOL_FLAG | 5u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 6u16,
    one: SYMBOL_FLAG | 7u16,
  },
  HuffmanNode {
    zero: 39u16,
    one: 52u16,
  },
  HuffmanNode {
    zero: 40u16,
    one: 51u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 8u16,
    one: SYMBOL_FLAG | 11u16,
  },
  HuffmanNode {
    zero: 208u16,
    one: 42u16,
  },
  HuffmanNode {
    zero: 43u16,
    one: 165u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 239u16,
    one: 44u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 9u16,
    one: SYMBOL_FLAG | 142u16,
  },
  HuffmanNode {
    zero: 55u16,
    one: 46u16,
  },
  HuffmanNode {
    zero: 63u16,
    one: 47u16,
  },
  HuffmanNode {
    zero: 147u16,
    one: 48u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 249u16,
    one: 49u16,
  },
  HuffmanNode {
    zero: 50u16,
    one: 59u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 10u16,
    one: SYMBOL_FLAG | 13u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 12u16,
    one: SYMBOL_FLAG | 14u16,
  },
  HuffmanNode {
    zero: 53u16,
    one: 54u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 15u16,
    one: SYMBOL_FLAG | 16u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 17u16,
    one: SYMBOL_FLAG | 18u16,
  },
  HuffmanNode {
    zero: 56u16,
    one: 60u16,
  },
  HuffmanNode {
    zero: 57u16,
    one: 58u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 19u16,
    one: SYMBOL_FLAG | 20u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 21u16,
    one: SYMBOL_FLAG | 23u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 22u16,
    one: SYMBOL_FLAG | 256u16,
  },
  HuffmanNode {
    zero: 61u16,
    one: 62u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 24u16,
    one: SYMBOL_FLAG | 25u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 26u16,
    one: SYMBOL_FLAG | 27u16,
  },
  HuffmanNode {
    zero: 64u16,
    one: 65u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 28u16,
    one: SYMBOL_FLAG | 29u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 30u16,
    one: SYMBOL_FLAG | 31u16,
  },
  HuffmanNode {
    zero: 85u16,
    one: 67u16,
  },
  HuffmanNode {
    zero: 68u16,
    one: 82u16,
  },
  HuffmanNode {
    zero: 143u16,
    one: 69u16,
  },
  HuffmanNode {
    zero: 70u16,
    one: 81u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 32u16,
    one: SYMBOL_FLAG | 37u16,
  },
  HuffmanNode {
    zero: 72u16,
    one: 79u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 33u16,
    one: SYMBOL_FLAG | 34u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 124u16,
    one: 74u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 35u16,
    one: SYMBOL_FLAG | 62u16,
  },
  HuffmanNode {
    zero: 76u16,
    one: 80u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 38u16,
    one: SYMBOL_FLAG | 42u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 63u16,
    one: 78u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 39u16,
    one: SYMBOL_FLAG | 43u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 40u16,
    one: SYMBOL_FLAG | 41u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 44u16,
    one: SYMBOL_FLAG | 59u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 45u16,
    one: SYMBOL_FLAG | 46u16,
  },
  HuffmanNode {
    zero: 83u16,
    one: 90u16,
  },
  HuffmanNode {
    zero: 84u16,
    one: 89u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 47u16,
    one: SYMBOL_FLAG | 51u16,
  },
  HuffmanNode {
    zero: 86u16,
    one: 130u16,
  },
  HuffmanNode {
    zero: 87u16,
    one: 88u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 48u16,
    one: SYMBOL_FLAG | 49u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 50u16,
    one: SYMBOL_FLAG | 97u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 52u16,
    one: SYMBOL_FLAG | 53u16,
  },
  HuffmanNode {
    zero: 91u16,
    one: 92u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 54u16,
    one: SYMBOL_FLAG | 55u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 56u16,
    one: SYMBOL_FLAG | 57u16,
  },
  HuffmanNode {
    zero: 99u16,
    one: 94u16,
  },
  HuffmanNode {
    zero: 138u16,
    one: 95u16,
  },
  HuffmanNode {
    zero: 142u16,
    one: 96u16,
  },
  HuffmanNode {
    zero: 97u16,
    one: 103u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 58u16,
    one: SYMBOL_FLAG | 66u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 60u16,
    one: SYMBOL_FLAG | 96u16,
  },
  HuffmanNode {
    zero: 100u16,
    one: 132u16,
  },
  HuffmanNode {
    zero: 101u16,
    one: 129u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 61u16,
    one: SYMBOL_FLAG | 65u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 64u16,
    one: SYMBOL_FLAG | 91u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 67u16,
    one: SYMBOL_FLAG | 68u16,
  },
  HuffmanNode {
    zero: 105u16,
    one: 112u16,
  },
  HuffmanNode {
    zero: 106u16,
    one: 109u16,
  },
  HuffmanNode {
    zero: 107u16,
    one: 108u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 69u16,
    one: SYMBOL_FLAG | 70u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 71u16,
    one: SYMBOL_FLAG | 72u16,
  },
  HuffmanNode {
    zero: 110u16,
    one: 111u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 73u16,
    one: SYMBOL_FLAG | 74u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 75u16,
    one: SYMBOL_FLAG | 76u16,
  },
  HuffmanNode {
    zero: 113u16,
    one: 116u16,
  },
  HuffmanNode {
    zero: 114u16,
    one: 115u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 77u16,
    one: SYMBOL_FLAG | 78u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 79u16,
    one: SYMBOL_FLAG | 80u16,
  },
  HuffmanNode {
    zero: 117u16,
    one: 118u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 81u16,
    one: SYMBOL_FLAG | 82u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 83u16,
    one: SYMBOL_FLAG | 84u16,
  },
  HuffmanNode {
    zero: 120u16,
    one: 136u16,
  },
  HuffmanNode {
    zero: 121u16,
    one: 122u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 85u16,
    one: SYMBOL_FLAG | 86u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 87u16,
    one: SYMBOL_FLAG | 89u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 88u16,
    one: SYMBOL_FLAG | 90u16,
  },
  HuffmanNode {
    zero: 125u16,
    one: 155u16,
  },
  HuffmanNode {
    zero: 126u16,
    one: 148u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 92u16,
    one: SYMBOL_FLAG | 195u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 93u16,
    one: SYMBOL_FLAG | 126u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 94u16,
    one: SYMBOL_FLAG | 125u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 95u16,
    one: SYMBOL_FLAG | 98u16,
  },
  HuffmanNode {
    zero: 131u16,
    one: 135u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 99u16,
    one: SYMBOL_FLAG | 101u16,
  },
  HuffmanNode {
    zero: 133u16,
    one: 134u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 100u16,
    one: SYMBOL_FLAG | 102u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 103u16,
    one: SYMBOL_FLAG | 104u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 105u16,
    one: SYMBOL_FLAG | 111u16,
  },
  HuffmanNode {
    zero: 137u16,
    one: 141u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 106u16,
    one: SYMBOL_FLAG | 107u16,
  },
  HuffmanNode {
    zero: 139u16,
    one: 140u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 108u16,
    one: SYMBOL_FLAG | 109u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 110u16,
    one: SYMBOL_FLAG | 112u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 113u16,
    one: SYMBOL_FLAG | 118u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 114u16,
    one: SYMBOL_FLAG | 117u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 115u16,
    one: SYMBOL_FLAG | 116u16,
  },
  HuffmanNode {
    zero: 145u16,
    one: 146u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 119u16,
    one: SYMBOL_FLAG | 120u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 121u16,
    one: SYMBOL_FLAG | 122u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 127u16,
    one: SYMBOL_FLAG | 220u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 208u16,
    one: 149u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 128u16,
    one: SYMBOL_FLAG | 130u16,
  },
  HuffmanNode {
    zero: 196u16,
    one: 151u16,
  },
  HuffmanNode {
    zero: 152u16,
    one: 178u16,
  },
  HuffmanNode {
    zero: 153u16,
    one: 158u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 230u16,
    one: 154u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 129u16,
    one: SYMBOL_FLAG | 132u16,
  },
  HuffmanNode {
    zero: 156u16,
    one: 175u16,
  },
  HuffmanNode {
    zero: 157u16,
    one: 204u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 131u16,
    one: SYMBOL_FLAG | 162u16,
  },
  HuffmanNode {
    zero: 159u16,
    one: 160u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 133u16,
    one: SYMBOL_FLAG | 134u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 136u16,
    one: SYMBOL_FLAG | 146u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 137u16,
    one: SYMBOL_FLAG | 138u16,
  },
  HuffmanNode {
    zero: 163u16,
    one: 164u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 139u16,
    one: SYMBOL_FLAG | 140u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 141u16,
    one: SYMBOL_FLAG | 143u16,
  },
  HuffmanNode {
    zero: 166u16,
    one: 171u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 144u16,
    one: SYMBOL_FLAG | 145u16,
  },
  HuffmanNode {
    zero: 168u16,
    one: 185u16,
  },
  HuffmanNode {
    zero: 169u16,
    one: 173u16,
  },
  HuffmanNode {
    zero: 170u16,
    one: 172u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 147u16,
    one: SYMBOL_FLAG | 149u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 148u16,
    one: SYMBOL_FLAG | 159u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 150u16,
    one: SYMBOL_FLAG | 151u16,
  },
  HuffmanNode {
    zero: 174u16,
    one: 181u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 152u16,
    one: SYMBOL_FLAG | 155u16,
  },
  HuffmanNode {
    zero: 241u16,
    one: 176u16,
  },
  HuffmanNode {
    zero: 177u16,
    one: 188u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 153u16,
    one: SYMBOL_FLAG | 161u16,
  },
  HuffmanNode {
    zero: 179u16,
    one: 183u16,
  },
  HuffmanNode {
    zero: 180u16,
    one: 182u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 154u16,
    one: SYMBOL_FLAG | 156u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 157u16,
    one: SYMBOL_FLAG | 158u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 160u16,
    one: SYMBOL_FLAG | 163u16,
  },
  HuffmanNode {
    zero: 184u16,
    one: 190u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 164u16,
    one: SYMBOL_FLAG | 169u16,
  },
  HuffmanNode {
    zero: 186u16,
    one: 194u16,
  },
  HuffmanNode {
    zero: 187u16,
    one: 189u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 165u16,
    one: SYMBOL_FLAG | 166u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 167u16,
    one: SYMBOL_FLAG | 172u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 168u16,
    one: SYMBOL_FLAG | 174u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 170u16,
    one: SYMBOL_FLAG | 173u16,
  },
  HuffmanNode {
    zero: 192u16,
    one: 218u16,
  },
  HuffmanNode {
    zero: 193u16,
    one: 234u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 171u16,
    one: SYMBOL_FLAG | 206u16,
  },
  HuffmanNode {
    zero: 195u16,
    one: 203u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 175u16,
    one: SYMBOL_FLAG | 180u16,
  },
  HuffmanNode {
    zero: 197u16,
    one: 235u16,
  },
  HuffmanNode {
    zero: 198u16,
    one: 202u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 176u16,
    one: SYMBOL_FLAG | 177u16,
  },
  HuffmanNode {
    zero: 200u16,
    one: 206u16,
  },
  HuffmanNode {
    zero: 201u16,
    one: 205u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 178u16,
    one: SYMBOL_FLAG | 181u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 179u16,
    one: SYMBOL_FLAG | 209u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 182u16,
    one: SYMBOL_FLAG | 183u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 184u16,
    one: SYMBOL_FLAG | 194u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 185u16,
    one: SYMBOL_FLAG | 186u16,
  },
  HuffmanNode {
    zero: 207u16,
    one: 210u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 187u16,
    one: SYMBOL_FLAG | 189u16,
  },
  HuffmanNode {
    zero: 209u16,
    one: 215u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 188u16,
    one: SYMBOL_FLAG | 191u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 190u16,
    one: SYMBOL_FLAG | 196u16,
  },
  HuffmanNode {
    zero: 212u16,
    one: 224u16,
  },
  HuffmanNode {
    zero: 213u16,
    one: 222u16,
  },
  HuffmanNode {
    zero: 214u16,
    one: 221u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 192u16,
    one: SYMBOL_FLAG | 193u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 197u16,
    one: SYMBOL_FLAG | 231u16,
  },
  HuffmanNode {
    zero: 217u16,
    one: 243u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 198u16,
    one: SYMBOL_FLAG | 228u16,
  },
  HuffmanNode {
    zero: 245u16,
    one: 219u16,
  },
  HuffmanNode {
    zero: 220u16,
    one: 244u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 199u16,
    one: SYMBOL_FLAG | 207u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 200u16,
    one: SYMBOL_FLAG | 201u16,
  },
  HuffmanNode {
    zero: 223u16,
    one: 228u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 202u16,
    one: SYMBOL_FLAG | 205u16,
  },
  HuffmanNode {
    zero: 237u16,
    one: 225u16,
  },
  HuffmanNode {
    zero: 248u16,
    one: 226u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 255u16,
    one: 227u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 203u16,
    one: SYMBOL_FLAG | 204u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 210u16,
    one: SYMBOL_FLAG | 213u16,
  },
  HuffmanNode {
    zero: 230u16,
    one: 249u16,
  },
  HuffmanNode {
    zero: 231u16,
    one: 239u16,
  },
  HuffmanNode {
    zero: 232u16,
    one: 233u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 211u16,
    one: SYMBOL_FLAG | 212u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 214u16,
    one: SYMBOL_FLAG | 221u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 215u16,
    one: SYMBOL_FLAG | 225u16,
  },
  HuffmanNode {
    zero: 236u16,
    one: 242u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 216u16,
    one: SYMBOL_FLAG | 217u16,
  },
  HuffmanNode {
    zero: 238u16,
    one: 246u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 218u16,
    one: SYMBOL_FLAG | 219u16,
  },
  HuffmanNode {
    zero: 240u16,
    one: 247u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 222u16,
    one: SYMBOL_FLAG | 223u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 224u16,
    one: SYMBOL_FLAG | 226u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 227u16,
    one: SYMBOL_FLAG | 229u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 232u16,
    one: SYMBOL_FLAG | 233u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 234u16,
    one: SYMBOL_FLAG | 235u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 236u16,
    one: SYMBOL_FLAG | 237u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 238u16,
    one: SYMBOL_FLAG | 240u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 241u16,
    one: SYMBOL_FLAG | 244u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 242u16,
    one: SYMBOL_FLAG | 243u16,
  },
  HuffmanNode {
    zero: 250u16,
    one: 253u16,
  },
  HuffmanNode {
    zero: 251u16,
    one: 252u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 245u16,
    one: SYMBOL_FLAG | 246u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 247u16,
    one: SYMBOL_FLAG | 248u16,
  },
  HuffmanNode {
    zero: 254u16,
    one: 255u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 250u16,
    one: SYMBOL_FLAG | 251u16,
  },
  HuffmanNode {
    zero: SYMBOL_FLAG | 252u16,
    one: SYMBOL_FLAG | 253u16,
  },
];

#[inline]
pub(super) fn step(node: u16, bit: u32) -> HuffmanStep {
  let Some(node) = HUFFMAN_NODES.get(usize::from(node)) else {
    return HuffmanStep::Invalid;
  };
  let next = if bit == 0 { node.zero } else { node.one };
  decode_edge(next)
}

#[inline]
fn decode_edge(edge: u16) -> HuffmanStep {
  if edge == INVALID_EDGE {
    HuffmanStep::Invalid
  } else if edge & SYMBOL_FLAG == SYMBOL_FLAG {
    HuffmanStep::Symbol(usize::from(edge & !SYMBOL_FLAG))
  } else {
    HuffmanStep::Node(edge)
  }
}
